version: '2.1'
services:
    ntp-server:
       image: siangyeh8818/ntp:v4
       container_name: ntp-server
       restart: always
       privileged: true
       environment:
         - NTP_CLUSTER_IP_LIST=172.16.106.130,172.16.106.131,172.16.106.132
         - NTP_NODE_USER=deployer
         - NTP_NODE_PASSWORD=Emotibot1
         - SPECIFY_NTP_SERVER=TOCK.stdtime.gov.tw
         - BIOS_TIME_CORRETCION=True
       volumes:
          - /etc/localtime:/etc/localtime
