apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ntp
  namespace: kube-system
  labels:
    k8s-app: ntp
spec:
  selector:
    matchLabels:
      name: ntp
  template:
    metadata:
      labels:
        name: ntp
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: ntp
        image: siangyeh8818/ntp:v4
        securityContext:
          privileged: true        
        env:
        - name: NTP_CLUSTER_IP_LIST
          value : "127.0.0.1"
        - name: NTP_NODE_USER
          value : "root"
        - name: NTP_NODE_PASSWORD
          value : "pentiumvm"
        - name: SPECIFY_NTP_SERVER
          value : "TOCK.stdtime.gov.tw"
        - name: BIOS_TIME_CORRETCION
          value : "True"
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
      terminationGracePeriodSeconds: 30
      volumes:
      - name: localtime
        hostPath:
          path: /etc/localtime

